# Uncorrected Hamiltonian Annealing (UHA) or (ULA-UD)
name: ula_ud
underdamped: True
integrator: OBABO
init_std: ${target.all.init_std}
friction: ${target.underdamped.friction}
learn_prior: ${target.all.learn_prior}
learn_betas: True
learn_friction: True
learn_mass_matrix: False

defaults:
  - dt_schedule: cosine