name: gaussian_mixture1d
dim: 1
has_entropy: False

fn:
  _target_: targets.gmm1d.GMM1D
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.1
  step_size: 5e-4
  batch_size: 2_000
  init_std: 1
  learn_prior: False
  target_score_max_norm:


