name: lgcp
dim: 1600
has_entropy: False

fn:
  _target_: targets.lgcp.LogGaussianCoxPines
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.1
  step_size: 5e-4
  batch_size: 500
  init_std: 1
  learn_prior: True
  target_score_max_norm:
