name: many_well
dim: 50
m: 5
delta: 2
has_entropy: False

fn:
  _target_: targets.many_well.ManyWellEnergy
  dim: ${target.dim}
  m: ${target.m}
  delta: ${target.delta}
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.1
  step_size: 5e-4
  batch_size: 2000
  init_std: 1.
  learn_prior: False
  target_score_max_norm: