name: nice_fashion
dim: 784
has_entropy: True

fn:
  _target_: targets.nice.NiceTarget
  dataset: fashion_mnist
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.5
  step_size: 5e-4
  batch_size: 500
  init_std: 5
  learn_prior: False
  target_score_max_norm: