name: phi4
dim: 64
kappa: 0.3
has_entropy: False

fn:
  _target_: targets.phi4.Phi4Distr
  dim: ${target.dim}
  kappa: ${target.kappa}
  lambd: 0.022
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 1.
  step_size: 5e-4
  batch_size: 500
  init_std: 1
  learn_prior: True
  target_score_max_norm:
