name: planar_robot
has_entropy: False
dim: 10

fn:
  _target_: targets.planar_robot.PlanarRobot
  dim: ${target.dim}
  num_goals: 1
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.1
  step_size: 5e-4
  batch_size: 2000
  init_std: 10.
  learn_prior: True
  target_score_max_norm: