name: rings
dim: 2
has_entropy: False

fn:
  _target_: targets.rings.ConcentricRings
  dim: ${target.dim}
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

underdamped:
  friction: 1.


overdamped:
  friction: 1.

all: # Parameters that are shared between all algorithms
  dt: 0.01
  step_size: 5e-4
  batch_size: 2000
  init_std: 5.
  learn_prior: False
  target_score_max_norm:
